### ISSUE TITLE
Codificação da imagem logo_ufs.eps incorreta.

### ISSUE THREAD

**Issue by lisboaigor** [DCOMP-UFS/abntex2-DCOMP-UFS#2]
## Resumo
O enconding da imagem está em um formato específico para MacOS que o MikTex não pode processar.
## Screenshot
![image](https://github.com/DCOMP-UFS/abntex2-DCOMP-UFS/assets/46612620/190cf343-b88b-42f0-8be2-ce133935edfa)

**Comment by bruno-prado** [comment]
@lisboaigor anexe o erro que está sendo gerado durante a compilação, não consigo reproduzir este erro nem no Overleaf nem no PDFLaTex.

**Comment by bruno-prado** [comment]
Acredito que com a mudança do formato de EPS para PDF, o problema está resolvido.
